### PR TITLE
Ubuntu 25.10 Compatibility

### LINKED ISSUE #347: Different '$PATH' variable when running nvim from terminal and from uLauncher
First of all, thanks for the amazing work in this setup. It's really good and really beautiful.
I am little newbie about writing issues in English. Here's the description:

If I run neovim through the launcher, its $PATH variable is different when i run from the alacritty terminal (alt+2 and then `nvim`). 
I know that, behind the scenes, it's all alacritty, but something is different.

After all, what's the problem?
During the omakub installation, i chose to install go, ruby, python and node. 
When I try to install (via Ulauncher) some nvim plugins (like pyright) which use node, or go, I have the following problem:
```
[ERROR Mon 02 Dec 2024 08:56:55 PM -03] ...e/nvim/lazy/mason.nvim/lua/mason-core/installer/init.lua:249: Installation failed for Package(name=goimports) error=spawn: go failed with exit code - and signal -. go is not executable
[INFO  Mon 02 Dec 2024 08:56:55 PM -03] ...e/nvim/lazy/mason.nvim/lua/mason-core/installer/init.lua:184: Executing installer for Package(name=erb-lint) {}
[ERROR Mon 02 Dec 2024 08:56:55 PM -03] ...e/nvim/lazy/mason.nvim/lua/mason-core/installer/init.lua:249: Installation failed for Package(name=markdownlint-cli2) error=spawn: npm failed with exit code - and signal -. npm is not executable
[INFO  Mon 02 Dec 2024 08:56:55 PM -03] ...e/nvim/lazy/mason.nvim/lua/mason-core/installer/init.lua:184: Executing installer for Package(name=bash-language-server) {}
[ERROR Mon 02 Dec 2024 08:56:55 PM -03] ...e/nvim/lazy/mason.nvim/lua/mason-core/installer/init.lua:249: Installation failed for Package(name=gofumpt) error=spawn: go failed with exit code - and signal -. go is not executable
[INFO  Mon 02 Dec 2024 08:56:55 PM -03] ...e/nvim/lazy/mason.nvim/lua/mason-core/installer/init.lua:184: Executing installer for Package(name=docker-compose-language-service) {}
[ERROR Mon 02 Dec 2024 08:56:55 PM -03] ...e/nvim/lazy/mason.nvim/lua/mason-core/installer/init.lua:249: Installation failed for Package(name=markdown-toc) error=spawn: npm failed with exit code - and signal -. npm is not executable
```
Via Launcher:
image
image

Via alacritty:
image

`mise list`:
image

I personally don't like using 'nvim via alacritty' because of some conflicting keymaps (like ctrl+b). 

Is there a way to make both $PATH's the same?

Thanks for your time.

### LINKED ISSUE #536: Opening folders in Alacritty from Files causes Files to freeze until terminal is closed
When I right-click a folder in Files and choose Open in Alacritty, the Files application freezes until I close Alacritty. While Alacritty is open, Files shows a popup asking whether to "Force Quit" or "Wait," and the right-click context menu also remains stuck on screen. Once I close Alacritty, Files resumes working normally.

### LINKED ISSUE #553: Unable to install on clear installed Ubuntu 25.10
Hello,

during the installation Omakub on just installed Ubuntu 25.10, I have got the following error: `Error: Package 'tldr' has no installation candidate`.
This also isn't worked.
```
sudo apt update
sudo apt install tldr
```

So, I have installed tldr via pipx manually. But it also did not help.

### LINKED ISSUE #558: omakub installation fails on Ubuntu 24.04 and 25.10 (Dell Vostro 3530)
I’m trying to install Omakub on my Dell Vostro 15 3530 laptop. I’ve set up a dual boot with Ubuntu and Windows 11.

When I run the installation script for the first time, it shows “installation failed.” 
However, when I try to rerun it using 
"source ~/.local/share/omakub/install.sh"
 It just closes the terminal.
I initially tried this on Ubuntu 25.10, but it failed, so I switched to Ubuntu 24.04 LTS, and I’m still facing the same issue.
Can anyone help me figure out what’s causing this and how to fix it?

Image

### PR DESCRIPTION
**Pull request by Kasui92**
This PR includes the main adjustments required to ensure Omakub installs and runs properly on **Ubuntu 25.10**. 

## What's Changed
* Update **Signal** install/uninstall scripts by @Kasui92
* Refactor **Typora** installation to use official repository and keyring by @Kasui92
* Simplify **1Password** installation by using direct download instead of repository setup by @Kasui92
* Replace flatpak installation with direct download and installation of **Obsidian** by @Kasui92
* Replace snap installation of **Pinta** with flatpak installation by @Kasui92
* Prevents keyring duplication in **VSCode** installation by @neidiom and @Kasui92
* Prevents keyring duplication in **Docker**, **Github CLI**, **Signal**, **Typora**, **Brave Browser**, **Windsurf** and **Spotify** installation by  @Kasui92
* Use Official PPA for **Ulauncher** installation by @Kasui92 
* Update uninstall script to remove **Neovim** files by @Kasui92
* Use `pipx` for `tldr` installation by @Kasui92
* Move `pipx` installation into libraries by @Kasui92
* Removed _Open with Alacritty_ option on Nautilus by @Kasui92
* Update `gum` version to 0.17.0 for improved functionality by @Kasui92
* Move _gir1-*_ installation into gnome-extensions step by @Kasui92
* Add fallback in reboot request by @Kasui92 

## Pending Fixes & Adjustments
- The colors provided for `accent-color` in Ubuntu 25.10 have changed from previous releases, fallbacks should be provided
- **BlurMyShell** has not yet been updated for compatibility with _Gnome 49_. There are several [PRs](https://github.com/aunetx/blur-my-shell/pull/791) that fix this
- The latest version of **LazyVim** supports `tree-sitter-cli`, which is missing from versions prior to Ubuntu 25.10. We'll need to consider either a fallback to the previous version of **LazyVim** or force the installation of `node` to update `tree-sitter-cli`

## How to Test the Update

For anyone interested in testing this update, a temporary installation script is provided below.  
This script is intended **only for testing purposes** on fresh or disposable environments (for example, a virtual machine).  
It is **not a production-ready update**, and should not be used on systems already running Omakub.  
Once the update is finalized, it will be included in the normal Omakub update flow.

```bash
wget -qO- https://omakasui.org/omakub | bash
```

## Fixing & Closing
Closes #554 
Closes #552 
Closes #510
Fixes #558 
Fixes #553 
Fixes #536 
Fixes #347

### CODE REVIEW

**Comment by neidiom** [comment]
Nice work, man.

File: install/desktop.sh [hunk 1]
```diff
@@ -4,4 +4,4 @@
 for installer in ~/.local/share/omakub/install/desktop/*.sh; do source $installer; done
 
 # Logout to pickup changes
-gum confirm "Ready to reboot for all settings to take effect?" && sudo reboot
+gum confirm "Ready to reboot for all settings to take effect?" && sudo reboot || true
```
Comment (dhh) [inline install/desktop.sh]: What is this `|| true` catching?

File: install/desktop/app-obsidian.sh [hunk 2]
```diff
@@ -1,5 +1,9 @@
...
 
 # Obsidian is a multi-platform note taking application. See https://obsidian.md
-gum spin --spinner meter --title "Obsidian installation about to start. It may take up to 20 minutes on some systems!" -- sleep 3
-flatpak install -y flathub md.obsidian.Obsidian
+cd /tmp
+OBSIDIAN_VERSION=$(curl -s https://api.github.com/repos/obsidianmd/obsidian-releases/releases/latest | grep -Po '"tag_name": "v\K[^"]*')
+wget -O obsidian.deb "https://github.com/obsidianmd/obsidian-releases/releases/latest/download/obsidian_${OBSIDIAN_VERSION}_amd64.deb"
+sudo apt install -y ./obsidian.deb
+rm obsidian.deb
+cd -
```
Comment (dhh) [inline install/desktop/app-obsidian.sh]: We are using flatpak elsewhere, so why move off it here?

Comment (Kasui92) [reply install/desktop/app-obsidian.sh]: It reduces installation time compared to flatpak and, if I'm not mistaken, it was in the best interests of using fewer flatpaks when possible.

Comment (dhh) [reply install/desktop/app-obsidian.sh]: I see. I am happy to see faster obsidian install. It's bizarrely slow with flatpak 👍

File: install/desktop/app-pinta.sh [hunk 3]
```diff
@@ -1,4 +1,4 @@
 #!/bin/bash
 
-# FIXME: Get this out of snap
-sudo snap install pinta
+# Pinta is a simple drawing and image editing program. See https://www.pinta-project.com/
+flatpak install -y flathub com.github.PintaProject.Pinta
```
[the remark this answers is not in the document]
Comment (dhh) [reply install/desktop/app-pinta.sh]: Nice!

File: install/terminal/apps-terminal.sh
Comment (TakiShiwa) [inline install/terminal/apps-terminal.sh]: Thank you for the fix. This tldr was giving an error when I tried today. The fix has been merged as I can see, how can I get the updated link to reinstall?
